import { mutation } from "./_generated/server";

export const run = mutation(async ({ db }) => {
  const existing = await db.query("companies").collect();
  if (existing.length) {
    return { status: "skipped", reason: "Data already exists" };
  }

  const now = Date.now();

  const [sferaId, inkassId, mkkId] = await Promise.all([
    db.insert("companies", {
      name: "Холдинг Сфера",
      inn: "7701234567",
      kpp: "770101001",
      comment: "Головная компания холдинга",
      contracts: 12,
      simCards: 95,
      employees: 78,
      monthlyExpense: 265000,
      createdAt: now,
    }),
    db.insert("companies", {
      name: "Инкасс Коллект",
      inn: "7702345678",
      kpp: "770201001",
      comment: "Инкассаторские услуги",
      contracts: 8,
      simCards: 64,
      employees: 48,
      monthlyExpense: 148000,
      createdAt: now,
    }),
    db.insert("companies", {
      name: "МКК ФК",
      inn: "7703456789",
      kpp: "770301001",
      comment: "Микрофинансовая компания",
      contracts: 4,
      simCards: 27,
      employees: 16,
      monthlyExpense: 76000,
      createdAt: now,
    }),
  ]);

  const [mtsId, beelineId, megafonId, rostelecomId, tele2Id, yotaId] = await Promise.all([
    db.insert("operators", {
      name: "МТС",
      type: "Мобильная связь",
      manager: "Петрова Анна",
      phone: "+7 (495) 123-00-00",
      email: "corp@mts.ru",
      contracts: 5,
      simCards: 78,
      createdAt: now,
    }),
    db.insert("operators", {
      name: "Билайн",
      type: "Мобильная связь",
      manager: "Сидоров Игорь",
      phone: "+7 (495) 234-00-00",
      email: "business@beeline.ru",
      contracts: 3,
      simCards: 42,
      createdAt: now,
    }),
    db.insert("operators", {
      name: "Мегафон",
      type: "Мобильная связь",
      manager: "Козлова Мария",
      phone: "+7 (495) 345-00-00",
      email: "corp@megafon.ru",
      contracts: 2,
      simCards: 25,
      createdAt: now,
    }),
    db.insert("operators", {
      name: "Ростелеком",
      type: "Интернет / IP-телефония",
      manager: "Иванова Елена",
      phone: "+7 (495) 567-00-00",
      email: "corporate@rt.ru",
      contracts: 6,
      simCards: 0,
      createdAt: now,
    }),
    db.insert("operators", {
      name: "Теле2",
      type: "Мобильная связь",
      manager: "Новиков Сергей",
      phone: "+7 (495) 456-00-00",
      email: "b2b@tele2.ru",
      contracts: 2,
      simCards: 22,
      createdAt: now,
    }),
    db.insert("operators", {
      name: "Yota",
      type: "Мобильная связь",
      manager: "Поддержка Yota",
      phone: "+7 (800) 550-00-07",
      email: "corp@yota.ru",
      contracts: 1,
      simCards: 10,
      createdAt: now,
    }),
  ]);

  const tariffIds = await Promise.all([
    db.insert("tariffs", {
      name: "Корпоративный L",
      operatorId: mtsId,
      monthlyFee: 1500,
      dataLimitGb: 50,
      minutes: 2000,
      sms: 500,
      status: "active",
      simCount: 45,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес Безлимит",
      operatorId: beelineId,
      monthlyFee: 1800,
      dataLimitGb: 999,
      minutes: 4000,
      sms: 1000,
      status: "active",
      simCount: 30,
      createdAt: now,
    }),
    // Малый бизнес 399-450 ₽
    db.insert("tariffs", {
      name: "Умный бизнес S",
      operatorId: mtsId,
      monthlyFee: 399,
      minutes: 300,
      dataLimitGb: 10,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес S",
      operatorId: megafonId,
      monthlyFee: 399,
      minutes: 1000,
      dataLimitGb: 50,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Старт",
      operatorId: rostelecomId,
      monthlyFee: 399,
      minutes: 500,
      dataLimitGb: 10,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес S",
      operatorId: tele2Id,
      monthlyFee: 399,
      minutes: 500,
      dataLimitGb: 20,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Гибкое решение Base",
      operatorId: beelineId,
      monthlyFee: 450,
      minutes: 500,
      dataLimitGb: 50,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Основной",
      operatorId: yotaId,
      monthlyFee: 450,
      minutes: 300,
      dataLimitGb: 50,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    // Средний бизнес 599-699 ₽
    db.insert("tariffs", {
      name: "Гибкое решение Medium",
      operatorId: beelineId,
      monthlyFee: 699,
      minutes: 1000,
      dataLimitGb: 100,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Расширенный",
      operatorId: yotaId,
      monthlyFee: 699,
      minutes: 1000,
      dataLimitGb: 100,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес M",
      operatorId: megafonId,
      monthlyFee: 649,
      minutes: 2000,
      dataLimitGb: 75,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес M",
      operatorId: tele2Id,
      monthlyFee: 649,
      minutes: 1500,
      dataLimitGb: 50,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Умный бизнес M",
      operatorId: mtsId,
      monthlyFee: 599,
      minutes: 600,
      dataLimitGb: 15,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Стандарт",
      operatorId: rostelecomId,
      monthlyFee: 599,
      minutes: 1200,
      dataLimitGb: 25,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    // Крупный бизнес 999-1699 ₽
    db.insert("tariffs", {
      name: "Гибкое решение Plus",
      operatorId: beelineId,
      monthlyFee: 1099,
      minutes: 2000,
      dataLimitGb: 200,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Полный",
      operatorId: yotaId,
      monthlyFee: 1099,
      minutes: 9999,
      dataLimitGb: 9999,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Умный бизнес XL",
      operatorId: mtsId,
      monthlyFee: 1699,
      minutes: 5000,
      dataLimitGb: 60,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес L",
      operatorId: megafonId,
      monthlyFee: 999,
      minutes: 3000,
      dataLimitGb: 100,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Премиум",
      operatorId: rostelecomId,
      monthlyFee: 999,
      minutes: 3000,
      dataLimitGb: 50,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("tariffs", {
      name: "Бизнес L",
      operatorId: tele2Id,
      monthlyFee: 999,
      minutes: 3000,
      dataLimitGb: 100,
      sms: undefined,
      status: "active",
      simCount: 0,
      createdAt: now,
    }),
  ]);

  const employees = await Promise.all([
    db.insert("employees", {
      name: "Иванов Иван Иванович",
      companyId: sferaId,
      department: "IT-отдел",
      position: "Системный администратор",
      status: "active",
      simCount: 3,
      maxSim: 20,
      createdAt: now,
    }),
    db.insert("employees", {
      name: "Петров Петр Петрович",
      companyId: sferaId,
      department: "Отдел продаж",
      position: "Менеджер по продажам",
      status: "active",
      simCount: 2,
      maxSim: 20,
      createdAt: now,
    }),
    db.insert("employees", {
      name: "Сидорова Анна Сергеевна",
      companyId: inkassId,
      department: "Финансовый отдел",
      position: "Главный бухгалтер",
      status: "active",
      simCount: 1,
      maxSim: 20,
      createdAt: now,
    }),
    db.insert("employees", {
      name: "Козлов Дмитрий Александрович",
      companyId: mkkId,
      department: "Отдел разработки",
      position: "Ведущий разработчик",
      status: "active",
      simCount: 4,
      maxSim: 20,
      createdAt: now,
    }),
    db.insert("employees", {
      name: "Новикова Елена Владимировна",
      companyId: sferaId,
      department: "HR-отдел",
      position: "HR-менеджер",
      status: "fired",
      simCount: 0,
      maxSim: 20,
      createdAt: now,
    }),
    db.insert("employees", {
      name: "Морозов Алексей Николаевич",
      companyId: inkassId,
      department: "Инкассация",
      position: "Старший инкассатор",
      status: "active",
      simCount: 5,
      maxSim: 20,
      createdAt: now,
    }),
  ]);

  const contracts = await Promise.all([
    db.insert("contracts", {
      number: "МТС-2024/001",
      companyId: sferaId,
      operatorId: mtsId,
      type: "Мобильная связь",
      status: "active",
      monthlyFee: 125000,
      startDate: "01.01.2024",
      endDate: "Бессрочный",
      simCount: 45,
      createdAt: now,
    }),
    db.insert("contracts", {
      number: "РТК-2024/015",
      companyId: inkassId,
      operatorId: rostelecomId,
      type: "Интернет (офис)",
      status: "active",
      monthlyFee: 48000,
      startDate: "15.03.2024",
      endDate: "14.03.2025",
      simCount: 0,
      createdAt: now,
    }),
    db.insert("contracts", {
      number: "БЛН-2024/008",
      companyId: mkkId,
      operatorId: beelineId,
      type: "Мобильная связь",
      status: "active",
      monthlyFee: 32000,
      startDate: "01.02.2024",
      endDate: "Бессрочный",
      simCount: 18,
      createdAt: now,
    }),
    db.insert("contracts", {
      number: "МГФ-2024/003",
      companyId: sferaId,
      operatorId: megafonId,
      type: "VPN / канал связи",
      status: "closing",
      monthlyFee: 28000,
      startDate: "01.06.2023",
      endDate: "31.12.2024",
      simCount: 0,
      createdAt: now,
    }),
  ]);

  const expenseRows = [
    { companyId: sferaId, month: "Ноябрь 2024", amount: 125340, vat: 20890, total: 146230, type: "Мобильная связь", contract: "МТС-2024/001", operator: "МТС", status: "confirmed", hasDocument: true },
    { companyId: inkassId, month: "Ноябрь 2024", amount: 48000, vat: 8000, total: 56000, type: "Интернет (офис)", contract: "РТК-2024/015", operator: "Ростелеком", status: "confirmed", hasDocument: true },
    { companyId: mkkId, month: "Ноябрь 2024", amount: 32450, vat: 5408, total: 37858, type: "Мобильная связь", contract: "БЛН-2024/008", operator: "Билайн", status: "draft", hasDocument: false },
    { companyId: sferaId, month: "Октябрь 2024", amount: 121200, vat: 20200, total: 141400, type: "Мобильная связь", contract: "МТС-2024/001", operator: "МТС", status: "confirmed", hasDocument: true },
    { companyId: sferaId, month: "Ноябрь 2024", amount: 28000, vat: 4667, total: 32667, type: "VPN/каналы", contract: "МГФ-2024/003", operator: "Мегафон", status: "adjusted", hasDocument: true },
  ];

  await Promise.all(
    expenseRows.map((row) =>
      db.insert("expenses", {
        ...row,
        status: (row as { status?: unknown }).status as "confirmed" | "draft" | "adjusted" | undefined,
        createdAt: now,
      }),
    ),
  );

  const simCardRows = [
    { companyId: sferaId, employeeId: employees[0], operatorId: mtsId, tariffId: tariffIds[0], number: "79001234567" },
    { companyId: sferaId, employeeId: employees[1], operatorId: mtsId, tariffId: tariffIds[0], number: "79007654321" },
    { companyId: inkassId, employeeId: employees[2], operatorId: beelineId, tariffId: tariffIds[1], number: "79005557766" },
    { companyId: mkkId, employeeId: employees[3], operatorId: megafonId, tariffId: tariffIds[0], number: "79009998877" },
  ];

  await Promise.all(
    simCardRows.map((row) =>
      db.insert("simCards", {
        ...row,
        status: "active",
        createdAt: now,
      }),
    ),
  );

  return {
    status: "seeded",
    companies: [sferaId, inkassId, mkkId].length,
    operators: [mtsId, beelineId, megafonId, rostelecomId].length,
    employees: employees.length,
    contracts: contracts.length,
  };
});
